"""The loop surface the controls call.

Named as a protocol so the service is typed against what it uses rather
than the whole :class:`~sbxloop.daemon.loop.DaemonLoop`, and so a test
double only has to answer the verbs a test exercises — the fakes the
chat tests already use satisfy it structurally.
"""

from __future__ import annotations

from typing import Any, Protocol

from sbxloop.config import ScheduleConfig
from sbxloop.daemon.controls.results import CancelOutcome, ResumeOutcome
from sbxloop.daemon.model import WorkItem


class ControlLoop(Protocol):
    dstore: Any

    @property
    def holds(self) -> list[str]: ...
    def status(self) -> dict[str, Any]: ...
    def pause(self, hold: str = ..., *, by: str | None = None) -> list[str]: ...
    def unpause(self, hold: str | None = ..., *, by: str | None = None) -> list[str]: ...
    def cancel_current(self, requester: str | None = None, *, retry: bool = False) -> bool: ...
    def cancel_provider(self, target: str, by: str | None = None) -> str: ...
    def cancel_run(
        self,
        run_id: str,
        *,
        by: str | None = None,
        retry: bool = False,
        expected_revision: int | None = None,
        operation_id: str | None = None,
    ) -> CancelOutcome: ...
    def resume_run(
        self, run_id: str, *, by: str | None = None, expected_revision: int | None = None
    ) -> ResumeOutcome: ...
    def steer_run(
        self,
        run_id: str,
        text: str,
        *,
        by: str | None = None,
        expected_revision: int | None = None,
    ) -> str: ...
    def resume_review(self, target: str, by: str | None = None) -> str: ...
    def grant_rounds(self, run_id: str, rounds: int, by: str | None = None) -> WorkItem: ...
    def resume_repo(self, repo: str, by: str | None = None) -> dict[str, Any]: ...
    def schedules(self) -> list[dict[str, Any]]: ...
    def add_schedule(self, spec: ScheduleConfig, by: str | None, *, source: str) -> str: ...
    def remove_schedule(self, name: str, by: str | None) -> str: ...
    def pause_schedule(self, name: str, by: str | None) -> str: ...
    def resume_schedule(self, name: str, by: str | None) -> str: ...
    def request_stop(self) -> None: ...
    def supervisor(self) -> str | None: ...
    def request_restart(
        self, *, by: str | None, reason: str, now: bool = False, **fields: Any
    ) -> None: ...
    def approve_merge(
        self, target: str, by: str | None = None, *, expected_revision: int | None = None
    ) -> str: ...
    def abandon_item(self, item_id: str, reason: str | None = None) -> WorkItem: ...
    def retry_item(self, item_id: str, by: str | None = None) -> WorkItem: ...
    def requeue_item(self, item_id: str) -> WorkItem: ...
    def clock(self) -> float: ...
